apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-cluster1
spec:
  version: 7.14.0
  count: 1
  elasticsearchRef:
    name: cluster1
  config:
    xpack.fleet.agents.elasticsearch.host: "https://cluster1-es-http.default.svc:9200"
    xpack.fleet.agents.fleet_server.hosts: ["https://fleet-server-agent-http.default.svc:8220"]
